name: Node.js CI

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    env:
      project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
      private_key: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      client_email: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
      api_key: ${{ secrets.FIREBASE_API_KEY }}
      user_email: ${{ vars.TEST_EMAIL }}
      user_password: ${{ vars.TEST_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - run: npm install
      - run: npm test
      - run: npm run build
      - run: npm run test:prod
